### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Abdallah-Fouad-X** [kleiton0x00/XSScope#1]
..

**Comment by Abdallah-Fouad-X** [comment]
it seems that the connect throw the ssh needed to change the permission for the keys ,

**Comment by kleiton0x00** [comment]
Hello, can you please tell me in details what the problem is? I will be happy to assist!

**Comment by Abdallah-Fouad-X** [comment]
Hello, 
when the app asked fore the ssh key , it need to change the key  permission : chmod 600 for the id_rsa and id_rsa.pub , this was the problem.
so when i change it it worked fine.
