### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [kleiton0x00/XSScope#12]
Hello,
When I run this script and open http://localhost:1337 I have this error  y don't happend nothing

```
The requested resource / was not found on this server.
```
A greeting and thanks

**Comment by kleiton0x00** [comment]
Why do you want to open the localhost:1337 in browser? Just use the program on the GUI itself.

Please take a look at the Demo to see how to correctly use the program:
https://github.com/kleiton0x00/XSScope/wiki/Demo
