### ISSUE TITLE
generating a browser shell

### ISSUE THREAD

**Issue by ChillVibesMushroom** [kleiton0x00/XSScope#13]
I'm a complete noob at this and I would like to learn how to generate a browser shell with xsscope on an android device

**Comment by kleiton0x00** [comment]
Getting a shell (hope you mean a reverse TCP shell) on an android device (and PC as well) via XSS in general is impossible. Please take a look [here](https://github.com/kleiton0x00/XSScope#features) to see what you can achieve by this tool.
