### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by pretech86** [kleiton0x00/XSScope#3]
i used the command python3 xsscope.py and i get this error 

python3 xsscope.py                                                                                                                                               1 ⨯
  File "xsscope.py", line 564
    os.chdir("..")
                 ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by kleiton0x00** [comment]
Please clone/download the project again as I made some small changes to fix that error. Let me know if that got fixed.

**Comment by pretech86** [comment]
i solved it thanks
