### ISSUE TITLE
website error 

### ISSUE THREAD

**Issue by pretech86** [kleiton0x00/XSScope#4]
when i try to goto 0.tcp.ngrok.io:11682 i get this 
The requested resource / was not found on this server.

and the xss payload not appeared it appeared as a blank page

**Comment by kleiton0x00** [comment]
You don't have to go to Ngrok website. If you really want to access it, you have to put your URL + Port in the browser.

For example: http://0.tcp.ngrok.io:13364

XSScope will automatically do everything for you, you don't need to access the URL. Just make sure ngrok is configured properly in ```setup.sh```
