### ISSUE TITLE
no payloads 

### ISSUE THREAD

**Issue by pretech86** [kleiton0x00/XSScope#5]
when i open payloads i get this ( blank screen )

![xsscope error](https://user-images.githubusercontent.com/46816468/99870311-34e62280-2be3-11eb-8b31-c3e18fe2b799.png)

**Comment by kleiton0x00** [comment]
Please send me the error displayed on the terminal. It is kinda weird to see this bug happens.

**Comment by pretech86** [comment]
SORRY for delaying 

└─$ python3 xsscope.py
[Sun Nov 22 02:58:34 2020] PHP 7.4.11 Development Server (http://localhost:1337) started
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "xsscope.py", line 646, in show_payload
    10] + cloudflare_bypass + list(tcp_server)[11] + cloudflare_bypass + list(tcp_server)[
IndexError: list index out of range

**Comment by kleiton0x00** [comment]
Please redownload the software as I made small changes. The problem is fixed.

**Comment by pretech86** [comment]
it's working thanks , but copy option not working

**Comment by kleiton0x00** [comment]
I think it is because ```pyperclip```module might not be properly installed in your Linux. Try to manually install that module by entering the following commands in your Terminal (hopefully 1 of them should work):

```sudo apt-get install python3-pyperclip```
```sudo python3 -m pip install pyperclip```
```pip3 install pyperclip```
